# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Brend'),
        ),
    ]
