# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171006_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
