# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171007_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='brend',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на картинку'),
        ),
    ]
